site_name: GeoBlacklight Documentation
site_url: https://geoblacklight.org/docs
#repo_url: https://github.com/geoblacklight/docs
theme:
     name: readthedocs
     logo: img/geoblacklight-logo-small@2x.png
     extra_css: docs/extra.css
     highlightjs: true
     titles_only: true
     include_homepage_in_sidebar: true
     analytics:
        gtag: G-RFL265H4YX

markdown_extensions:
  - admonition
  - def_list

extra_css:
  - extra.css
  
nav:
- GeoBlacklight Homepage: 'https://geoblacklight.org'
- Overview:
     - 'What is GeoBlacklight': 'overview/what_is_geoblacklight.md'
     - 'Contributing to GeoBlacklight': 'overview/contributing.md'
     - 'Metadata': 'overview/metadata.md'
     - 'Releases': 'overview/releases.md'
- Installation:
     - 'Quick Start': 'installation/geoblacklight_quick_start.md'
     - 'Getting Started - Developers Guide': 'installation/getting_started_developers.md'
- Configuration:
     - 'Settings Reference': 'configuration/settings.md'
     - 'Updating the Catalog Controller': 'configuration/catalog_controller.md'
- Customization:
     - 'Adding Leaflet Controls': 'customization/adding_leaflet_controls.md'
     - 'Configuring Leaflet for Retina Displays': 'customization/leaflet_retina_configuration.md'
     - 'Using the Data Relations Widget': 'customization/data_relations_widget.md'
     - 'Configuring Index Maps': 'customization/index_maps.md'
     - 'Switching Default Basemap': 'customization/default_basemap.md'
     - 'Dynamic Basemap Switching': 'customization/dynamic_basemap_switching.md'
     - 'Adding Support for Item Images': 'customization/item_images.md'
     - 'Adding Mirador IIIF Manifest Viewer': 'customization/adding_mirador_viewer.md'
     - 'Accessing Raster and Vector Layers in GeoPackages': 'customization/accessing_geopackages.md'
     - 'Adding SVG Icons': 'customization/adding_svg_icons.md'
     - 'Rendering Line Breaks or HTML from the Description Field': 'customization/rendering_html_from_description.md'
     - 'Homepage Map Centroid Clusters': 'customization/homepage_map_centroid_clusters.md'
- Running in Production:
     - 'Hardware Recommendations': 'production/hardware_recommendations.md'
     - 'Implementation Recommendations': 'production/implementation_recommendations.md'
     - 'Periodic Maintenance': 'production/periodic_maintenance.md'
- Upgrading:
     - 'Upgrading to Version 4.0': 'upgrading/Upgrading_to_version_4_0.md'
     - 'Upgrading to Version 2.0': 'upgrading/Upgrading_to_version_2_0.md'

#- Tutorials:
#     - 'Tutorials': 'tutorials/tutorials.md'
