site_name: GeoBlacklight Documentation
site_url: https://geoblacklight.org/docs
#repo_url: https://github.com/geoblacklight/docs
theme:
     name: material
     logo: img/geoblacklight-logo-small@2x.png
     extra_css: docs/extra.css
     features:
        - navigation.tabs
        - navigation.expand
#     highlightjs: true
#     titles_only: true
#     include_homepage_in_sidebar: true
     analytics:
        gtag: G-RFL265H4YX
     palette:
        primary: white
        accent: green
        
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:       
      toc_depth: 2

extra_css:
  - stylesheets/extra.css
  
nav:
#- GeoBlacklight Homepage: 'https://geoblacklight.org'

#- About:
#    - 'What is GeoBlacklight': 'overview/what_is_geoblacklight.md'
#    - 'Contributing to GeoBlacklight': 'overview/contributing.md'

- Home: 'index.md'

- Tutorials:
     - 'Setting up your environment': 'tutorials/setting-up-your-environment.md'
     - 'Quick Start': 'installation/geoblacklight_quick_start.md'
     - 'Developers Guide': 'installation/getting_started_developers.md'
     - 'Getting Started': 'tutorials/introduction-tutorial.md'

- How-to Guides:
     Map customizations:
        - 'Leaflet Controls': 'customization/adding_leaflet_controls.md'
        - 'Retina Displays': 'customization/leaflet_retina_configuration.md'
        - 'Default Basemap': 'customization/default_basemap.md'
        - 'Dynamic Basemap Switching': 'customization/dynamic_basemap_switching.md'
        - 'Centroid Clusters': 'customization/homepage_map_centroid_clusters.md'
     
     Image and icon customizations:
        - 'Item Images': 'customization/item_images.md'
        - 'Mirador IIIF Manifest Viewer': 'customization/adding_mirador_viewer.md'
        - 'SVG Icons': 'customization/adding_svg_icons.md'

     Item page customizations:
        - 'Rendering HTML in metadata fields': 'customization/rendering_html_from_description.md'

     Upgrading:
        - 'Upgrade to Version 4.0': 'upgrading/Upgrading_to_version_4_0.md'
        - 'Upgrade to Version 2.0': 'upgrading/Upgrading_to_version_2_0.md'

- Reference:
     - 'Metadata': 'overview/metadata.md'
     - 'Running in Production': 'running-in-production.md'
     - 'Accessing Raster and Vector Layers in GeoPackages': 'customization/accessing_geopackages.md'
     - 'The Data Relations Widget': 'customization/data_relations_widget.md'
     - 'Configuring Index Maps': 'customization/index_maps.md'







#- Tutorials:
#     - 'Tutorials': 'tutorials/tutorials.md'
